### ISSUE TITLE
TOC does not alway get displayed

### ISSUE THREAD

**Issue by rgreinho** [codeandmedia/zola_easydocs_theme#11]
When going to https://easydocs.codeandmedia.com/deployment/netlify/, we can see that the page has other sections ("Automatic deploys" and "Manual deploys"), but yet does not appear in the sidebar:

<img width="687" alt="image" src="https://user-images.githubusercontent.com/6969134/177227291-a417d9ee-97e6-4e2e-abcc-a0bf7fa3b203.png">

However when going to https://easydocs.codeandmedia.com/deployment/github-pages/, all the subsections appear correctly:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/6969134/177227325-3685e649-a1ad-40dc-8daf-1603daaf0823.png">

**Comment by codeandmedia** [comment]
TOC will be showed if we have more then 4 headers on particular page. You can change this number here https://github.com/codeandmedia/zola_easydocs_theme/blob/40baf660bf70d627218830613fc65b6fbefa0892/templates/index.html#L90
