### ISSUE TITLE
Support nested sections in nav

### ISSUE THREAD

**Issue by spectria-limina** [codeandmedia/zola_easydocs_theme#20]
Currently, the nav on the left-hand side doesn't support nested sections, even when you are visiting a section's own page.

Example directory structure:

```
content/
├── section/
   ├── subsection/
        ├── _index.md
    ├── _index.md
```

Expected: The "subsection" appears in the left nav under "section"
Actual: "subsection" is not visible in the left nav at all.

**Comment by codeandmedia** [comment]
Hi @spectria-limina ! Yes, you can add another nested subsection for both navigation and folders structure, just by copy-paste the current one.

**Comment by c-git** [comment]
@spectria-limina do you know exactly how many levels you need?
