### ISSUE TITLE
Add documentation for how to use theme as a theme instead of a fork

### ISSUE THREAD

**Issue by stevenroose** [codeandmedia/zola_easydocs_theme#24]
I think that is the recommended way by Zola, do submodule or copy the theme's repo into the `/themes` folder.

**Comment by c-git** [comment]
Yeah I'd brought it up [before](https://github.com/codeandmedia/zola_easydocs_theme/pull/12#issuecomment-1200228736) but I guess I never got around to the PR (I don't even see it on my todo list anymore).
