### ISSUE TITLE
Failed to render

### ISSUE THREAD

**Issue by ghost** [codeandmedia/zola_easydocs_theme#3]
When trying the easydocs theme I get the following when running the zola start.bat

Error: Failed to render page 'C:/git\Help\help\content\recordview\datatab\index.md'
Reason: Failed to render 'easydocs/templates/page.html' (error happened in a parent template)
Reason: Variable `page.toc` not found in context while rendering 'easydocs/templates/page.html'

My current page.html file in the theme template:
{% extends "index.html" %}
{% block title %} {{ config.title }} | {{ page.title }} {% endblock title %}
    {% block content %}
        {{ page.content | safe }}
    {% endblock content %}

**Comment by codeandmedia** [comment]
I wrapped page navigation with If, should be ok now, try to pull new code from the repo. If you would have any issues -- do not hestitate to send me link to you repo

**Comment by ghost** [comment]
Thanks. I was able to run the start.bat but then received a zola page saying I needed a section.html file. I've added the one I use for the book theme but Page with no sub pages don't display. Is there a section.html for easydocs?

**Comment by codeandmedia** [comment]
Easy docs have pretty flat arch. You could have only articles inside one folder. If you need sections -- take a look to docs as code theme
