### ISSUE TITLE
Tables without borders

### ISSUE THREAD

**Issue by Petrichor31** [codeandmedia/zola_easydocs_theme#4]
Hello,

The markdown tables are rendered without borders.
How can it be modifed?

**Comment by codeandmedia** [comment]
Hi @Petrichor31 , I added borders (see example [here](https://easydocs.codeandmedia.com/content/page/#markdown-table). Feel free to customise  it in sass [here](https://github.com/codeandmedia/zola_easydocs_theme/blob/74717fe8dcd813644187b3146287790237c03b27/sass/main.scss#L67)

**Comment by Petrichor31** [comment]
Cool thank you!
