### ISSUE TITLE
Are pull requests desirable?

### ISSUE THREAD

**Issue by c-git** [codeandmedia/zola_easydocs_theme#5]
Thank you very much for all your work really like the theme. I've needed to make a few modifications for my use of it. I wanted to know if you would want me to open a pull request with those features that could be considered as optional.

The only important change that I want to make that would not be backward compatible is changing the name of index.html as the base so that  index.html could be used for the landing page. However, if you are keen on pull requests I will not make this change.

Happy to explain the changes I'm talking about if you are interested. It's things like allowing the link to the logo to not need to be an absolute reference but an asset within the page. (PS the current implementation is not backward compatible but it can be updates such that it would be.)

**Comment by codeandmedia** [comment]
hi @c-git , thanks for warm words. You can fork the theme and change index.html. The main idea behind the theme - is to easily add your docs without any settings, so landing could be additional iteration. But anyway will be happy to review any PR you'll make

**Comment by c-git** [comment]
Thank you for the response and the explanation on the idea behind the theme. I'll pick the changes I've made that are in keeping with that and submit the PR.
